<a href="https://colab.research.google.com/github/Preethijenitha/Google-Stock-Prediction/blob/main/google_stock_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
a=pd.read_csv('/content/indexData.csv')
a

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0
...,...,...,...,...,...,...,...,...
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

In [3]:
a.columns

Index(['Index', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [4]:
a.shape

(112457, 8)

In [5]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112457 entries, 0 to 112456
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Index      112457 non-null  object
 1   Date       112457 non-null  object
 2   Open       110253 non-null  float64
 3   High       110253 non-null  float64
 4   Low        110253 non-null  float64
 5   Close      110253 non-null  float64
 6   Adj Close  110253 non-null  float64
 7   Volume     110253 non-null  float64
dtypes: float64(6), object(2)
memory usage: 6.9+ MB

In [6]:
a.isnull().sum()

Index           0
Date            0
Open         2204
High         2204
Low          2204
Close        2204
Adj Close    2204
Volume       2204
dtype: int64

In [7]:
a.fillna(method='ffill',inplace=True)

/tmp/ipython-input-7-1870026900.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  a.fillna(method='ffill',inplace=True)

In [8]:
a.isnull().sum()

Index        0
Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [9]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
a['Date']=label_encoder.fit_transform(a['Date'])
a['Date'].unique()

array([  258,   259,   260, ...,  3723,  3754, 14730])

In [10]:
x=a[['Date', 'Open', 'High', 'Low', 'Close','Adj Close']]
x

         Date         Open         High          Low        Close    Adj Close
0         258   528.690002   528.690002   528.690002   528.690002   528.690002
1         259   527.210022   527.210022   527.210022   527.210022   527.210022
2         260   527.840027   527.840027   527.840027   527.840027   527.840027
3         261   531.119995   531.119995   531.119995   531.119995   531.119995
4         262   532.070007   532.070007   532.070007   532.070007   532.070007
...       ...          ...          ...          ...          ...          ...
112452  14725  1241.119995  1251.910034  1241.119995  1247.069946  1247.069946
112453  14726  1249.469971  1259.209961  1249.030029  1256.599976  1256.599976
112454  14727  1256.079956  1258.880005  1248.140015  1248.930054  1248.930054
112455  14728  1254.609985  1265.660034  1254.609985  1258.579956  1258.579956
112456  14729  1258.489990  1263.709961  1258.239990  1263.619995  1263.619995

[112457 rows x 6 columns]

In [11]:
y=a[['Volume']]
y

             Volume
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
...             ...
112452  379696400.0
112453  160773400.0
112454   91173700.0
112455  155179900.0
112456  148465000.0

[112457 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [13]:
xtrain.shape

(89965, 6)

In [14]:
xtest.shape

(22492, 6)

In [15]:
ytrain.shape

(89965, 1)

In [16]:
ytest.shape

(22492, 1)

In [17]:
from sklearn.metrics import r2_score
from sklearn import linear_model
b = linear_model.Lasso(alpha=0.1)
b.fit(xtrain,ytrain)
ypred=b.predict(xtest)
score=r2_score(ytest,ypred)
print(score)

0.04157506664087873

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.993e+23, tolerance: 1.674e+20
  model = cd_fast.enet_coordinate_descent(

In [18]:
prediction = b.predict([[261,531.119995,531.119995,531.119995,531.119995,531.119995]])
print(prediction)

[-9.72699172e+08]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(